server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: studiopathania@gmail.com
    password: udjzscioqrjlnrtc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: myjwtsecretkeymyjwtsecretkey123456  # at least 32 chars
  expiration: 3600000  # 1 hour in ms
